#!/usr/bin/env bash

LOG_LEVEL=Info
PORTAL=https://portal.dymium.local:3001/
CONNECTOR=4a87fb02-f76c-4a0d-82b1-cfdcc23bdb6b
KEY=QtWHYSxMFeXG
SECRET=Ec0HnhNm4UtwNrKBFZC69ptQMD9UwNQF7Ngh-OnUxUfJGL3L8pNXQreZDA10g2hdlyLX8QTkLWv0PhOkXrkn9J7fL2tILvbxGABKvaVU0NzT6ZAY0sp2yQxJAXezhovp
CUSTOMER=spoofcorp
TUNNELSERVER=portal.dymium.local:3009
LOCAL_ENVIRONMENT=true
HEALTHPORT=9911
LOCAL_SEARCH=

set -x
docker run --rm  \
	--add-host=portal.dymium.local:192.168.0.104 \
	-e LOG_LEVEL="$LOG_LEVEL" \
	-e PORTAL="$PORTAL" \
	-e CONNECTOR="$CONNECTOR" \
	-e KEY="$KEY" \
	-e SECRET="$SECRET" \
	-e CUSTOMER="$CUSTOMER" \
	-e TUNNELSERVER="$TUNNELSERVER" \
	-e LOCAL_ENVIRONMENT="$LOCAL_ENVIRONMENT" \
	-e HEALTHPORT="$HEALTHPORT" \
	-e LOCAL_SEARCH="$LOCAL_SEARCH" \
	dymiumconnector
