#!/usr/bin/env bash

LOG_LEVEL=Debug
HEALTHPORT=10101
PORTAL=https://portal.dev.dymium.us/
CONNECTOR=57150152-a641-4e81-b0a9-b8916c6f2890
KEY=F52URLIoZYkW
SECRET=edjQNUODroiiDItsaMVUcPwmJ5wM5GCQa3Oa5xE85LA13jXQxuFIcgbSvIDPQofcKC0f9mu6GUrSG5QkEr0wV0BI0cVe5wr-49uoGJMDzQTk9HBZ6piLNy08i-gSa1yw
CUSTOMER=spoofcorp
TUNNELSERVER=spoofcorp.dev.dymium.us:3009
LOCAL_ENVIRONMENT=true

set -x
docker run --rm  \
	-e LOG_LEVEL="$LOG_LEVEL" \
	-e PORTAL="$PORTAL" \
	-e CONNECTOR="$CONNECTOR" \
	-e KEY="$KEY" \
	-e SECRET="$SECRET" \
	-e CUSTOMER="$CUSTOMER" \
	-e TUNNELSERVER="$TUNNELSERVER" \
	-e LOCAL_ENVIRONMENT="$LOCAL_ENVIRONMENT" \
	-e HEALTHPORT="$HEALTHPORT" \
	-e LOCAL_SEARCH="$LOCAL_SEARCH" \
	dymiumconnector
