FROM golang:1.20-buster


RUN apt-get update &&            \
    apt-get upgrade -y &&        \
    apt-get install -y           \
      build-essential            \
      postgresql-server-dev-all  \
      libmariadb3 libmariadb-dev \
      freetds-dev                \
      openjdk-11-jdk             \
      curl wget unzip zip        \
      snapd                      \
      libaio1 &&                 \
    mkdir -p /opt/oracle

#install gradle
RUN wget -c https://services.gradle.org/distributions/gradle-8.4-bin.zip -P /tmp
RUN unzip -d /opt/gradle /tmp/gradle-8.4-bin.zip

COPY ./instantclient* /opt/oracle/

RUN echo /opt/oracle/@instantclient_version@ > /etc/ld.so.conf.d/oracle-instantclient.conf && \
    ldconfig

ENV ORACLE_HOME=/opt/oracle/@instantclient_version@

ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/bin/aws-lambda-rie

ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/bin/aws-lambda-rie
RUN apt-get --allow-releaseinfo-change update
RUN apt-get update && apt-get install -y \
        freetds-bin \
        freetds-dev \
        freetds-common

RUN mkdir /db2_cli_odbc_driver
COPY ./v11.5.4_linuxx64_odbc_cli.tar.gz /db2_cli_odbc_driver
RUN cd /db2_cli_odbc_driver && tar xvf v11.5.4_linuxx64_odbc_cli.tar.gz

COPY ./db2_home/include /db2_cli_odbc_driver/odbc_cli/clidriver/include

ENV DB2_CLI_DRIVER_INSTALL_PATH="/db2_cli_odbc_driver/odbc_cli/clidriver"
ENV LD_LIBRARY_PATH="/db2_cli_odbc_driver/odbc_cli/clidriver/lib:/opt/ibm/db2/V11.5/lib64:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
ENV LIBPATH="/db2_cli_odbc_driver/odbc_cli/clidriver/lib:$LIBPATH"
ENV IBM_DB_HOME="/db2_cli_odbc_driver/odbc_cli/clidriver"
ENV CGO_CFLAGS="-I/db2_cli_odbc_driver/odbc_cli/clidriver/include"
ENV CGO_LDFLAGS="-L/db2_cli_odbc_driver/odbc_cli/clidriver/lib"

ENV GRADLE_HOME=/opt/gradle/gradle-8.4
ENV PATH="/opt/gradle/gradle-8.4/bin:${PATH}"

RUN apt-get install -y unixodbc unixodbc-dev
