#!/usr/bin/env bash
cd ../Tunnels/go/client/
go get -u ./...
cd ../server
go get -u ./...
cd ../meshconnector
go get -u ./...
cd ../meshserver
go get -u ./...
cd ../../../DbSync/go
go get -u ./...
cd ../../DbAnalyzer/go
go get -u ./...
cd ../../DbGuardian/go
cd ../../libs/go/dlog
go get -u ./...
cd ../log
go get -u ./...
cd ../go-kinesis
go get -u ./...
cd ../aws
go get -u ./...
cd ../../../web/go/src
go get -u ./...

