// this file is automatically generated.
// !!! DO NOT EDIT !!!

package types



type ConnectionType string
const (
  CT_PostgreSQL ConnectionType = "PostgreSQL"
  CT_MySQL ConnectionType = "MySQL"
)

type DataSemantics string
const (
  DS_FamilyName DataSemantics = "FamilyName"
  DS_Email DataSemantics = "Email"
  DS_SSN DataSemantics = "SSN"
)


