// this file is automatically generated.
// !!! DO NOT EDIT !!!

package types





type Column struct {
   Name string `json:"name"`
   Position int `json:"position"`
   Typ string `json:"typ"`
   Reference *Reference `json:"reference"`
   Semantics *DataSemantics `json:"semantics"`
}

type Connection struct {
   Typ ConnectionType `json:"typ"`
   Address string `json:"address"`
   Port int `json:"port"`
   User string `json:"user"`
   Password string `json:"password"`
   Database string `json:"database"`
   Tls bool `json:"tls"`
}

type Database struct {
   Name string `json:"name"`
   Schemas []Schema `json:"schemas"`
}

type Reference struct {
   Schema string `json:"schema"`
   Table string `json:"table"`
   Column string `json:"column"`
}

type Schema struct {
   Name string `json:"name"`
   Tables []Table `json:"tables"`
}

type Table struct {
   Name string `json:"name"`
   Columns []Column `json:"columns"`
}
