// this file is automatically generated.
// !!! DO NOT EDIT !!!

package main





type Column struct {
   Name string `json:"name"`
   Position int `json:"position"`
   Typ string `json:"typ"`
   Reference *string `json:"reference"`
   Semantics *DataSemantics `json:"semantics"`
}

type Connection struct {
   Typ ConnectionType `json:"typ"`
   Address string `json:"address"`
   Port int `json:"port"`
   User string `json:"user"`
   Database string `json:"database"`
   Tls bool `json:"tls"`
}

type Database struct {
   Name string `json:"name"`
   Schemas []Schema `json:"schemas"`
}

type Result struct {
   Databases []Database `json:"databases"`
}

type Schema struct {
   Name string `json:"name"`
   Tables []Table `json:"tables"`
}

type Table struct {
   Name string `json:"name"`
   Columns []Column `json:"columns"`
}
