
//Postgresql
POST http://localhost:8080/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "postgresql",
  "host": "localhost",
  "port": 5433,
  "database": "adventureworks",
  "properties": "",
  "user": "postgres",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "postgresql",
  "host": "localhost",
  "port": 5433,
  "database": "adventureworks",
  "properties": "",
  "user": "postgres",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "postgresql",
  "host": "localhost",
  "port": 5433,
  "database": "adventureworks",
  "properties": "",
  "user": "postgres",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtables/person
Content-Type: application/json

{
  "dbType": "postgresql",
  "host": "localhost",
  "port": 5433,
  "database": "adventureworks",
  "properties": "",
  "user": "postgres",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/person/person
Content-Type: application/json

{
  "dbType": "postgresql",
  "host": "localhost",
  "port": 5433,
  "database": "adventureworks",
  "properties": "",
  "user": "postgres",
  "password": "1234"
}
###

// MAtView - specific for postgresql
POST http://localhost:8080/api/dbanalyzer/dbcolumns/person/vstateprovincecountryregion
Content-Type: application/json

{
  "dbType": "postgresql",
  "host": "localhost",
  "port": 5433,
  "database": "adventureworks",
  "properties": "",
  "user": "postgres",
  "password": "1234"
}

###
POST http://localhost:8080/api/dbanalyzer/dbcolumns/adventureworks/employee
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3308,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

//Mysql
POST http://localhost:8080/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3308,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3308,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3308,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtables/adventureworks
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3308,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/adventureworks/employee
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3308,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

//MariaDB
POST http://localhost:8080/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3307,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3307,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3307,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtables/adventureworks
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3307,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/adventureworks/employee
Content-Type: application/json

{
  "dbType": "mysql",
  "host": "localhost",
  "port": 3307,
  "database": "adventureworks",
  "properties": "",
  "user": "root",
  "password": "1234"
}
###


//SQL Server
POST http://localhost:8080/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "sqlserver",
  "host": "localhost",
  "port": 1433,
  "database": "AdventureWorks2017",
  "properties": "",
  "user": "sa",
  "password": "Aa123456!"
}
###

POST http://localhost:8080/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "sqlserver",
  "host": "localhost",
  "port": 1433,
  "database": "AdventureWorks2017",
  "properties": "",
  "user": "sa",
  "password": "Aa123456!"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "sqlserver",
  "host": "localhost",
  "port": 1433,
  "database": "AdventureWorks2017",
  "properties": "",
  "user": "sa",
  "password": "Aa123456!"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtables/person
Content-Type: application/json

{
  "dbType": "sqlserver",
  "host": "localhost",
  "port": 1433,
  "database": "AdventureWorks2017",
  "properties": "",
  "user": "sa",
  "password": "Aa123456!"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/person/Person
Content-Type: application/json

{
  "dbType": "sqlserver",
  "host": "localhost",
  "port": 1433,
  "database": "AdventureWorks2017",
  "properties": "",
  "user": "sa",
  "password": "Aa123456!"
}
###

//Oracle
POST http://localhost:8080/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "oracle",
  "host": "localhost",
  "port": 1521,
  "database": "XEPDB1",
  "properties": "",
  "user": "NORTHWIND",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "oracle",
  "host": "localhost",
  "port": 1521,
  "database": "XEPDB1",
  "properties": "",
  "user": "NORTHWIND",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "oracle",
  "host": "localhost",
  "port": 1521,
  "database": "XEPDB1",
  "properties": "",
  "user": "NORTHWIND",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtables/NORTHWIND
Content-Type: application/json

{
  "dbType": "oracle",
  "host": "localhost",
  "port": 1521,
  "database": "XEPDB1",
  "properties": "",
  "user": "NORTHWIND",
  "password": "1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/NORTHWIND/EMPLOYEES
Content-Type: application/json

{
  "dbType": "oracle",
  "host": "localhost",
  "port": 1521,
  "database": "XEPDB1",
  "properties": "",
  "user": "NORTHWIND",
  "password": "1234"
}
###

//DB2
POST http://localhost:8080/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtables/ADEVENTUREWORKS
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/ADVENTUREWORKS/EMPLOYEE
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtables/CHATGPT
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/CHATGPT/CHATGPT
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/CHATGPT/CHATGPT_1
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###


//Mongo
POST http://localhost:8080/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "mongodb",
  "host": "localhost",
  "port": 27017,
  "database": "northwind2",
  "properties": "authSource=admin&ssl=false",
  "user": "admin",
  "password": "admin"
}
###

POST http://localhost:8080/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "mongodb",
  "host": "localhost",
  "port": 27017,
  "database": "northwind2",
  "properties": "authSource=admin&ssl=false",
  "user": "admin",
  "password": "admin"
}
###

POST http://localhost:8080/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "mongodb",
  "host": "localhost",
  "port": 27017,
  "database": "northwind2",
  "properties": "authSource=admin&ssl=false",
  "user": "admin",
  "password": "admin"
}

###

POST http://localhost:8080/api/dbanalyzer/dbtables/northwind2
Content-Type: application/json

{
  "dbType": "mongodb",
  "host": "localhost",
  "port": 27017,
  "database": "northwind2",
  "properties": "authSource=admin&ssl=false",
  "user": "admin",
  "password": "admin"
}

###

POST http://localhost:8080/api/dbanalyzer/dbcolumns/ADVENTUREWORKS/EMPLOYEE
Content-Type: application/json

{
  "dbType": "db2",
  "host": "localhost",
  "port": 50000,
  "database": "northwin",
  "properties": "",
  "user": "db2inst1",
  "password": "dymium1234"
}
###


//elasticsearch
POST http://localhost:8888/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbtabtypes
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbtables
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbtables
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###


POST http://localhost:8888/api/dbanalyzer/dbcolumns/nyc_restaurants
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/nyc_restaurants
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbsample?table=nyc_restaurants&samplesize=5
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###

POST http://localhost:8888/api/dbanalyzer/dbsample?table=nyc_restaurants&samplesize=5
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9200,
  "database": "test-cluster",
  "properties": "",
  "user": "elastic",
  "password": "admin123"
}
###


POST http://localhost:9200/_sql?format=txt
Content-Type: application/json
Authorization: Basic ZWxhc3RpYzphZG1pbjEyMw==

{
  "query": "SELECT * FROM nyc_restaurants LIMIT 20",
  "field_multi_value_leniency": true
}
###

POST http://localhost:9200/_sql
Content-Type: application/json
Authorization: Basic ZWxhc3RpYzphZG1pbjEyMw==

{
  "query": "SELECT * FROM nyc_restaurants LIMIT 20",
  "field_multi_value_leniency": true
}
###

GET http://localhost:9200/nyc_restaurants/_settings
Authorization: Basic ZWxhc3RpYzphZG1pbjEyMw==
###

GET http://localhost:9211/_settings
Authorization: Basic ZWxhc3RpYzpJbG92ZWJ1bGJz
###

GET http://localhost:9200/test_cluster/_settings
Authorization: Basic ZWxhc3RpYzphZG1pbjEyMw==
###



POST http://localhost:8888/api/dbanalyzer/dbping
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbschemas
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/resturant_data
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbtables
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/store
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/store5
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/store
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbsample?table=store&samplesize=9
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbsample?table=store&samplesize=9
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/store1
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/store4
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/store2
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/store2
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs"
}
###

POST http://localhost:8888/api/dbanalyzer/dbsample?table=store2&samplesize=9
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "host.docker.internal",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs",
  "columns": "double_field,date_field"
}
###

POST http://localhost:8888/api/dbanalyzer/dbsample?table=store2&samplesize=9
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "localhost",
  "port": 9211,
  "database": "http-es-cluster",
  "properties": "",
  "user": "elastic",
  "password": "Ilovebubs",
  "columns": "double_field,date_field"
}
###

POST http://localhost:9211/_sql
Content-Type: application/json
Authorization: Basic elastic:Ilovebulbs

{
  "query": "SELECT * FROM store LIMIT 9",
  "field_multi_value_leniency": true
}
###

POST http://localhost:8888/api/dbanalyzer/dbtables
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "https://b579d9f0c1cd4aebb80a680add525195.us-west-2.aws.found.io",
  "port": 443,
  "database": "b579d9f0c1cd4aebb80a680add525195",
  "properties": "",
  "user": "elastic",
  "password": "0yw2MvF9iUGMvDzF54IeCqmD"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/test_map
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "https://b579d9f0c1cd4aebb80a680add525195.us-west-2.aws.found.io",
  "port": 443,
  "database": "b579d9f0c1cd4aebb80a680add525195",
  "properties": "",
  "user": "elastic",
  "password": "0yw2MvF9iUGMvDzF54IeCqmD"
}
###


POST http://localhost:8888/api/dbanalyzer/dbcolumns/data_range_field
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "https://b579d9f0c1cd4aebb80a680add525195.us-west-2.aws.found.io",
  "port": 443,
  "database": "b579d9f0c1cd4aebb80a680add525195",
  "properties": "",
  "user": "elastic",
  "password": "0yw2MvF9iUGMvDzF54IeCqmD"
}
###

POST http://localhost:8888/api/dbanalyzer/dbcolumns/test_map
Content-Type: application/json

{
  "dbType": "elasticsearch",
  "host": "https://b579d9f0c1cd4aebb80a680add525195.us-west-2.aws.found.io",
  "port": 443,
  "database": "b579d9f0c1cd4aebb80a680add525195",
  "properties": "",
  "user": "elastic",
  "password": "0yw2MvF9iUGMvDzF54IeCqmD"
}
###