// this file is automatically generated.
// !!! DO NOT EDIT !!!

package types





type AuthorizationCodeRequest struct {
   Customerid string `json:"customerid"`
   Code string `json:"code"`
}

type AuthorizationCodeResponse struct {
   Token string `json:"token"`
   Name string `json:"name"`
   Groups []string `json:"groups"`
}

type CSRResponse struct {
   Certificate string `json:"certificate"`
}

type CertificateRequest struct {
   Csr string `json:"csr"`
}

type CertificateRequestWithSecret struct {
   Customer string `json:"customer"`
   Key string `json:"key"`
   Secret string `json:"secret"`
   Csr string `json:"csr"`
}

type CustomerIDRequest struct {
   Customerid string `json:"customerid"`
}

type CustomerIDResponse struct {
   LoginURL string `json:"loginURL"`
   Lbaddress string `json:"lbaddress"`
   Lbport int `json:"lbport"`
   ProtocolVersion string `json:"protocolVersion"`
   ClientMajorVersion string `json:"clientMajorVersion"`
   ClientMinorVersion string `json:"clientMinorVersion"`
}

type RequestUpdate struct {
   ProtocolVersion string `json:"protocolVersion"`
   ClientMajorVersion string `json:"clientMajorVersion"`
   ClientMinorVersion string `json:"clientMinorVersion"`
}
