// this file is automatically generated.
// !!! DO NOT EDIT !!!

package types



type ConnectionType string
const (
  CT_PostgreSQL ConnectionType = "PostgreSQL"
  CT_MySQL ConnectionType = "MySQL"
  CT_MariaDB ConnectionType = "MariaDB"
  CT_SqlServer ConnectionType = "SqlServer"
  CT_OracleDB ConnectionType = "OracleDB"
)

type DataSemantics string
const (
  DS_FamilyName DataSemantics = "FamilyName"
  DS_Email DataSemantics = "Email"
  DS_SSN DataSemantics = "SSN"
)

type GroupMapping struct {
   Id *string `json:"id"`
   Dymiumgroup string `json:"dymiumgroup"`
   Directorygroup string `json:"directorygroup"`
   Comments string `json:"comments"`
}
