// this file is automatically generated.
// !!! DO NOT EDIT !!!

package types



type Action string
const (
  A_Return Action = "return"
  A_Update Action = "update"
  A_Delete Action = "delete"
)

type Request struct {
   Action Action `json:"action"`
   Customer string `json:"customer"`
   Datascope *string `json:"datascope"`
}
