// this file is automatically generated.
// !!! DO NOT EDIT !!!

package types





type Arc struct {
   From_schema string `json:"from_schema"`
   From_table string `json:"from_table"`
   From_column string `json:"from_column"`
   To_schema string `json:"to_schema"`
   To_table string `json:"to_table"`
   To_column string `json:"to_column"`
}

type Column struct {
   Name string `json:"name"`
   Position int `json:"position"`
   Typ string `json:"typ"`
   IsNullable bool `json:"isNullable"`
   Default *string `json:"default"`
   Reference *Reference `json:"reference"`
   Semantics *DataSemantics `json:"semantics"`
}

type Connection struct {
   Typ ConnectionType `json:"typ"`
   Address string `json:"address"`
   Port int `json:"port"`
   User string `json:"user"`
   Password string `json:"password"`
   Database string `json:"database"`
   Tls bool `json:"tls"`
}

type Database struct {
   Name string `json:"name"`
   Schemas []Schema `json:"schemas"`
   Refs []Arc `json:"refs"`
}

type Reference struct {
   Schema string `json:"schema"`
   Table string `json:"table"`
   Column string `json:"column"`
}

type Schema struct {
   Name string `json:"name"`
   IsSystem bool `json:"isSystem"`
   Tables []Table `json:"tables"`
}

type Table struct {
   Name string `json:"name"`
   IsSystem bool `json:"isSystem"`
   Columns []Column `json:"columns"`
}
