#!/bin/bash
echo "$2"/dymiumgui.app/Contents/MacOS/dymium
echo ln -s "$2"/dymiumgui.app/Contents/MacOS/dymium /usr/local/bin/dymium
rm /usr/local/bin/dymium
ln -s "$2"/dymiumgui.app/Contents/MacOS/dymium /usr/local/bin/dymium
