#!/bin/sh

# simple script to facilitate connection to the DB in the cloud
# use it only as a template!

myName="<your name>"
stagingPort=5444
productionPort=5443

myPrivateKey=~/.ssh/"<your ssh key>"

# port where your end of the tunnel will be sitting
# standard value is 5432, but probably it is better to reserve
# it for your local DB

[ "$1" = "-k" ] && {
    k="yes"
    shift    
}

if [ "$1" = "production" ]
then
    echo "Production DB does not exist yet!"
    exit 255
    # db="db"
    # myDbPort=${productionPort}
elif [ "$1" = "staging" ]
then
    # db="customers.chx4y1j1dev2.us-west-2.rds.amazonaws.com"
    db="db.dymium.internal"
    myDbPort=${stagingPort}
else
    echo "Usage: zdb [-k] staging|production"
    exit 1
fi

if [ "$k" = "yes" ]
then
    pid=$(lsof -i TCP:${myDbPort} | sed 1d | awk '{print $2}')
    [ -z "$pid" ] || {
	echo "killing $pid..."
	kill $pid
    }
else
    ssh -o "StrictHostKeyChecking no" -nNT -i $myPrivateKey -L${myDbPort}:${db}:5432 ${myName}@bastion.dymium.us&
fi
