#!/bin/sh

# simple script to facilitate connection to the DB in the cloud
# use it only as a template!

myName="<your name>"
myPrivateKey=~/.ssh/"<your ssh key>"

# port where your end of the tunnel will be sitting
# standard value is 5432, but probably it is better to reserve
# it for your local DB
dymiumPort=5442
productionPort=5443
stagingPort=5444
devPort=5445


[ "$1" = "-k" ] && {
    k="yes"
    shift    
}

case "$1" in
    "dymium")
	bastion="bastion.dymium.us"
	db="db.dymium.internal"
	myDbPort=${dymiumPort}
	;;
    "production")
	myDbPort=${productionPort}
	echo "option 'production' is not supported yet"
	exit 255
	;;
    "staging")
	bastion="bastion.dymium.net"
	db="customers.comlwgjclrwa.us-west-2.rds.amazonaws.com"
	myDbPort=${stagingPort}
	;;
    "dev")
	# db="db.dymium.local"
	myDbPort=${devPort}
	echo "option '$1' is not supported yet"
	exit 255
	;;
    "")
	echo "Usage: $0 [-k] [dymium|production|staging|dev]"
	exit 255
	;;
    *)
	echo "option '$1' is not supported yet"
	exit 255
	;;
esac

if [ "$k" = "yes" ]
then
    pid=$(lsof -i TCP:${myDbPort} | sed 1d | awk '{print $2}')
    [ -z "$pid" ] || {
	echo "killing $pid..."
	kill $pid
    }
else
    set -x
    ssh -o "StrictHostKeyChecking no" -nNT -i $myPrivateKey -L${myDbPort}:${db}:5432 ${myName}@${bastion}
fi
