#!/bin/sh

# simple script to facilitate connection to the DB in the cloud
# use it only as a template!

myName="CHANGE: your name on bastion"
myPrivateKey=~/.ssh/"CHANGE: your SSH key"

# port where your end of the tunnel will be sitting
# standard value is 5432, but probably it is better to reserve
# it for your local DB


TARGET=${TARGET:-spoofcorp.guardian.local}
TARGET_PORT=${TARGET_PORT:-5432}

[ "$1" = "-k" ] && {
    k="yes"
    shift    
}

case "$1" in
    "dymium")
	PORT=9092
	BASTION=bastion.dymium.us
	shift
	;;
    "staging")
	PORT=9094
	BASTION=bastion.dymium.net
	shift
	;;
    *)
	echo "Usage: $0 [-k] [dymium|staging]"
	echo "option '$0' not supported"
	;;
esac

if [ "$k" = "yes" ]
then
    pid=$(lsof -i TCP:${PORT} | sed 1d | awk '{print $2}')
    [ -z "$pid" ] || {
	echo "killing $pid..."
	kill $pid
    }
else
    set -x
    ssh -o "StrictHostKeyChecking no" -nNT -i $myPrivateKey -L${PORT}:${TARGET}:${TARGET_PORT} ${myName}@${BASTION}
fi
