#!/bin/sh

# simple script to facilitate connection to the DB in the cloud
# use it only as a template!

PORT=${PORT:-9290}
TARGET=${TARGET:-spoofcorp.guardian.local}
TARGET_PORT=${TARGET_PORT:-5432}

myName="<your name>"
myPrivateKey=~/.ssh/"<your private key>"

# port where your end of the tunnel will be sitting
# standard value is 5432, but probably it is better to reserve
# it for your local DB

[ "$1" = "-k" ] && {
    k="yes"
    shift    
}

if [ "$k" = "yes" ]
then
    pid=$(lsof -i TCP:${PORT} | sed 1d | awk '{print $2}')
    [ -z "$pid" ] || {
	echo "killing $pid..."
	kill $pid
    }
else
    set -x
    ssh -o "StrictHostKeyChecking no" -nNT -i $myPrivateKey -L${PORT}:${TARGET}:${TARGET_PORT} ${myName}@bastion.dymium.us&
fi
